### ISSUE TITLE
There is a trailing space in each blank line.

### ISSUE THREAD

**Issue by gxc** [antoyo/vim-licenses#10]
I love this Vim plugin. It's awesome.
Although there are plenty ways to strip trailing whitespaces, it would be perfect if no extra step needed.

![apache_license_trailing_spaces](https://cloud.githubusercontent.com/assets/1271862/12145978/34db2b66-b4cc-11e5-9b95-845c492cbd75.jpg)
![gpl_license_trailing_spaces](https://cloud.githubusercontent.com/assets/1271862/12145999/542777b8-b4cc-11e5-93f9-c3c776078570.jpg)
![mit_license_trailing_spaces](https://cloud.githubusercontent.com/assets/1271862/12146011/5ead154e-b4cc-11e5-96f4-4096111b18bc.jpg)

**Comment by antoyo** [comment]
That's a feature that I need too.
I'll try to implement it soon.

**Comment by tarkook** [comment]
This tiny [patch](https://github.com/antoyo/vim-licenses/files/392399/0001-Avoid-trailing-whitespaces-in-blank-lines.patch.zip) fixes the problem.

**Comment by antoyo** [comment]
@tarkook Thanks for your work!
