### ISSUE TITLE
Does not appear to work correctly with vim-tup

### ISSUE THREAD

**Issue by kozross** [antoyo/vim-licenses#14]
I'm trying to use this with [vim-tup][1] to put license headers on my Tupfiles. However, when I use a license-adding command (such as ``:Gpl``), it gives C-style comments instead of tup comments. Syntax highlighting for comments works correctly, and the filetype is set to ``tup`` correctly. I'm using the latext Neovim (``--version`` gives ``v0.2.0``).

[1]: https://github.com/dunedain289/vim-tup

**Comment by antoyo** [comment]
This is probably caused by the `comments` setting not set in this `vim-tup` plugin.
Try setting it to see if it fixes the issue.
You might want to use an `autocmd` or make a pull request in this plugin.

**Comment by kozross** [comment]
@antoyo I'm not surprised, given its age. I don't know exactly how to set this setting - what exactly does it have to say?

**Comment by antoyo** [comment]
I don't know this `tup` format, but try something like this:
```vim
set comments=s1:{-,mb:-,ex:-}
```
where `{-` is the start of a comment, `-` is the middle (inserted at every line) and `-}` is the end of a comment.

For a language supporting only single-line comment, try something like that:
```vim
set comments=:--
```
where `--` is the start of a single-line comment.

**Comment by kozross** [comment]
I have sent a PR for this upstream. Thank you for your help - will close this.
