### ISSUE TITLE
Doesn't work correctly for awk files

### ISSUE THREAD

**Issue by kozross** [antoyo/vim-licenses#17]
vim-licenses seems to put C-like comments into awk files (i.e. those files where ``set filetype?`` gives ``awk``). Syntax highlighting (and comments) for this are built-in for vim, so it should 'just work' right?

**Comment by antoyo** [comment]
What do you mean by the comments are built-in for vim?
When I look at the comments option for awk, I get the following: `comments=s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-`.
It seems that this is wrong in vim and needs to be adjusted [here](https://github.com/antoyo/vim-licenses/blob/master/plugin/licenses.vim#L75-L90).

**Comment by kozross** [comment]
@antoyo I'm happy to make a PR to that effect.

**Comment by antoyo** [comment]
I had a quick look at the `awk` ftplugin file and it does not have the variable `comments` set. However, it has the `commentstring` variable.
What you could do is look at this variable if the `comments` variable is the default. If the `comments` variable is the default and this `commentstring` variable is not empty, use the `commentstring`.
Beware that this `commentstring` can contain the start and end of a multiline comment, so we have to detect it somehow.

I don't know about vim, but neovim seems to have added the missing `comments` setting for some language like python, so we might want to remove these hard-coded default for these language as well.
Thanks for your help.

**Comment by kozross** [comment]
This is now fixed by commit #19.
